### ISSUE TITLE
Running batch experiment from ReplicationsSensitivity.gaml with facet keep_simulations to false raise exception at init

### ISSUE THREAD

**Issue by chapuisk** [COMOKIT/COMOKIT-Model#31]
The batch simulations run smoothly, but as soon as `keep_simulations` facet is set to false, it raises an exception. It seems that experiment agent try to access variables from the simulation agent (see `init {}` block in Abstract batch experiment.gaml) : 

1 occurence in Sensitivity0 at cycle 0: This experiment does not keep its simulations. DEFAULT_DATASETS_FOLDER_NAME cannot be retrieved in this context
in string build_dataset_path (string _datasets_folder_path <- project_path + DEFAULT_DATASETS_FOLDER_NAME, string _case_study_folder_name <- DEFAULT_CASE_STUDY_FOLDER_NAME)

Somehow related to a closed issue in Gama : https://github.com/gama-platform/gama/issues/2727

**Comment by AlexisDrogoul** [comment]
Well, this seems quite normal: DEFAULT_DATASETS_FOLDER_NAME is defined in the model/simulation and cannot be accessed by the experiment. I have however relaxed the constraints a little bit for the constants. I will commit soon.

**Comment by AlexisDrogoul** [comment]
Should be fixed (at least for constants) in https://github.com/gama-platform/gama/commit/ac17bc33241004169238942449757dcc82661f91

**Comment by chapuisk** [comment]
We are still not able to launch batch with facet ``keep_simulation: false`` ! It might requires to move all path management in experiments.

**Comment by AlexisDrogoul** [comment]
Have you checked if you are running the latest version ?

**Comment by AlexisDrogoul** [comment]
I've pushed another fix for the special case of constants, it should be ok now.
